import { ResumeData, ThemeConfig, SECTION_IDS } from '@/types';
import { generateId } from '@/lib/utils';

export const sampleResumeData: ResumeData = {
  personalInfo: {
    fullName: 'Md. Abdullah Al Mamun',
    fatherName: 'Md. Abdul Karim',
    motherName: 'Fatema Begum',
    dateOfBirth: '1995-03-15',
    gender: 'Male',
    maritalStatus: 'Single',
    nationality: 'Bangladeshi',
    religion: 'Islam',
    bloodGroup: 'B+',
    presentAddress: 'House #12, Road #5, Dhanmondi, Dhaka-1205',
    permanentAddress: 'Village: Uttar Para, P.O: Sadar, P.S: Sadar, Dist: Comilla',
    phone: '+880-1712-345678',
    email: 'mamun@example.com',
    nid: '1234567890123',
    photo: '',
  },
  careerObjective:
    'To secure a challenging position in a reputable organization where I can utilize my skills and knowledge to contribute to the growth of the organization while enhancing my professional development.',
  education: [
    {
      id: generateId(),
      degree: 'Bachelor of Science in Computer Science & Engineering',
      institution: 'Bangladesh University of Engineering and Technology (BUET)',
      university: 'BUET',
      board: '',
      subject: 'CSE',
      yearOfPassing: '2018',
      duration: '4 Years',
      result: '',
      cgpa: '3.75',
      grade: '',
    },
    {
      id: generateId(),
      degree: 'Higher Secondary Certificate (HSC)',
      institution: 'Dhaka College',
      university: '',
      board: 'Dhaka',
      subject: 'Science',
      yearOfPassing: '2013',
      duration: '2 Years',
      result: '',
      cgpa: '',
      grade: 'GPA-5.00',
    },
    {
      id: generateId(),
      degree: 'Secondary School Certificate (SSC)',
      institution: 'Comilla Zilla School',
      university: '',
      board: 'Comilla',
      subject: 'Science',
      yearOfPassing: '2011',
      duration: '2 Years',
      result: '',
      cgpa: '',
      grade: 'GPA-5.00',
    },
  ],
  experience: [
    {
      id: generateId(),
      organization: 'Tech Solutions Bangladesh Ltd.',
      designation: 'Senior Software Engineer',
      department: 'Engineering',
      location: 'Dhaka, Bangladesh',
      startDate: '2021-06',
      endDate: '',
      isCurrent: true,
      responsibilities:
        '• Led a team of 5 developers for web application development\n• Implemented RESTful APIs using Node.js and Express\n• Optimized database queries resulting in 40% performance improvement\n• Conducted code reviews and mentored junior developers',
    },
    {
      id: generateId(),
      organization: 'Software Paradigm International',
      designation: 'Software Engineer',
      department: 'Development',
      location: 'Dhaka, Bangladesh',
      startDate: '2018-09',
      endDate: '2021-05',
      isCurrent: false,
      responsibilities:
        '• Developed and maintained enterprise web applications\n• Built responsive UI components using React.js\n• Collaborated with cross-functional teams for product delivery\n• Participated in agile development processes',
    },
  ],
  skills: [
    { id: generateId(), name: 'JavaScript', level: 90, category: 'Technical' },
    { id: generateId(), name: 'TypeScript', level: 85, category: 'Technical' },
    { id: generateId(), name: 'React.js', level: 88, category: 'Technical' },
    { id: generateId(), name: 'Node.js', level: 82, category: 'Technical' },
    { id: generateId(), name: 'Python', level: 75, category: 'Technical' },
    { id: generateId(), name: 'MongoDB', level: 78, category: 'Technical' },
    { id: generateId(), name: 'PostgreSQL', level: 72, category: 'Technical' },
    { id: generateId(), name: 'Git', level: 85, category: 'Technical' },
    { id: generateId(), name: 'Docker', level: 65, category: 'Technical' },
    { id: generateId(), name: 'Communication', level: 80, category: 'Soft' },
    { id: generateId(), name: 'Team Leadership', level: 75, category: 'Soft' },
    { id: generateId(), name: 'Problem Solving', level: 88, category: 'Soft' },
  ],
  projects: [
    {
      id: generateId(),
      title: 'E-Commerce Platform',
      description:
        'A full-stack e-commerce solution with payment gateway integration, inventory management, and admin dashboard.',
      technologies: 'Next.js, Node.js, MongoDB, Stripe',
      url: 'https://github.com/mamun/ecommerce',
      startDate: '2023-01',
      endDate: '2023-06',
    },
    {
      id: generateId(),
      title: 'Task Management System',
      description:
        'A collaborative task management tool with real-time updates, team features, and progress tracking.',
      technologies: 'React, TypeScript, Firebase, Tailwind CSS',
      url: 'https://github.com/mamun/task-manager',
      startDate: '2022-08',
      endDate: '2022-12',
    },
  ],
  certifications: [
    {
      id: generateId(),
      title: 'AWS Certified Solutions Architect',
      issuingOrganization: 'Amazon Web Services',
      issueDate: '2023-03',
      expiryDate: '2026-03',
      credentialId: 'AWS-123456',
      url: 'https://aws.amazon.com/certification',
    },
  ],
  trainings: [
    {
      id: generateId(),
      title: 'Advanced Web Development',
      institution: 'Bangladesh Computer Council',
      duration: '3 Months',
      year: '2020',
      description: 'Comprehensive training on modern web technologies.',
    },
  ],
  languages: [
    {
      id: generateId(),
      language: 'Bengali',
      read: true,
      write: true,
      speak: true,
      proficiency: 'Native',
    },
    {
      id: generateId(),
      language: 'English',
      read: true,
      write: true,
      speak: true,
      proficiency: 'Fluent',
    },
  ],
  references: [
    {
      id: generateId(),
      name: 'Dr. Mohammad Rahman',
      designation: 'Professor',
      organization: 'BUET, CSE Department',
      relationship: 'Academic Advisor',
      phone: '+880-1711-111111',
      email: 'rahman@buet.ac.bd',
      address: 'Dhaka, Bangladesh',
    },
    {
      id: generateId(),
      name: 'Mr. Kamal Hossain',
      designation: 'CTO',
      organization: 'Tech Solutions Bangladesh Ltd.',
      relationship: 'Reporting Manager',
      phone: '+880-1722-222222',
      email: 'kamal@techsolutions.com.bd',
      address: 'Dhaka, Bangladesh',
    },
  ],
  interests: [
    { id: generateId(), interest: 'Open Source Contribution' },
    { id: generateId(), interest: 'Technical Writing' },
    { id: generateId(), interest: 'Cricket' },
    { id: generateId(), interest: 'Reading' },
  ],
  socialLinks: [
    {
      id: generateId(),
      platform: 'LinkedIn',
      url: 'https://linkedin.com/in/mamun',
    },
    {
      id: generateId(),
      platform: 'GitHub',
      url: 'https://github.com/mamun',
    },
  ],
  customSections: [],
  declaration: {
    text: 'I hereby declare that all the information provided above is true and correct to the best of my knowledge and belief.',
    date: '',
    signatureImage: '',
    showDeclaration: true,
  },
};

export const defaultTheme: ThemeConfig = {
  primaryColor: '#2563eb',
  textColor: '#1f2937',
  headingBgColor: '#dbeafe',
  headingTextColor: '#1e3a8a',
  fontFamily: 'Inter, sans-serif',
  fontSize: 14,
  spacing: 12,
  borderRadius: 4,
  template: 'two-column',
  themePreset: 'professional',
};

export const defaultSectionOrder = [...SECTION_IDS];

export const defaultSectionVisibility: Record<string, boolean> = {
  personal: true,
  objective: true,
  education: true,
  experience: true,
  skills: true,
  projects: true,
  certifications: true,
  trainings: true,
  languages: true,
  references: true,
  interests: true,
  social: true,
  custom: false,
  declaration: true,
};
